name: Deploy to Oracle VM Server

on:
  push:
    branches: [jd] # Or the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: List files in source directory
        run: pwd  #To get souce patch for SCP

      - name: Test Build
        run: npm test

      - name: Deploy on Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "/home/runner/work/react-light-table-master/react-light-table-master/*"
          target: "/home/opc/v2/"


      # - name: Deploy on Remote Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     script: |
      #       cd /home/opc/v2
      #       pwd
      #       mkdir check-dir
      #       ls -lah
      #       git pull origin master
      #       git status
      #       npm install