name: Deploy to Oracle VM Server

on:
  push:
    branches: [jd] # Or the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # - name: Test Build
      #   run: npm test

      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd ~/home/opc/v2
            git pull origin master
            git status
            npm install